<?php

namespace Database\Seeders;

use App\Models\Post;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $s1 = Post::create([
            'titulo'=>'rerum facil jlñj is est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit',
            'contenido'=>'th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/f4KzA5G89zpAAKLqK5uRMNLHCSjzh14LeqwhWGXg.jpg",
            'titulo_en'=>'Interpretative skills are the foundation of interacting in the target',
            'contenido_en'=>'Our services will help you build the foundation of a new language or brush up on your skills in a previously acquired language that’s been out of practice. Our targeted, goal-based teaching methodologies provide an engaging, motivating environment. Our services are facilitated by modern technology, offering both at home and on the go access Our services will help you build the foundation of a new language or brush up on your skills in a previously acquired language that’s been out of practice. Our targeted, goal-based teaching methodologies provide an engaging, motivating environment. Our services are facilitated by modern technology, offering both at home and on the go access',
            'titulo_it'=>'Questo sito realizza la motivante possibilità di imparare nuove lingue',
            'contenido_it'=>'Questo sito realizza la motivante possibilità di imparare nuove lingue straniere grazie a una stimolante tecnologia, disponibile sia per chi vuole acquisire le basi di una lingua che per chi desidera ampliare le conoscenze sviluppate nei percorsi scolastici Questo sito realizza la motivante possibilità di imparare nuove lingue straniere grazie a una stimolante tecnologia, disponibile sia per chi vuole acquisire le basi di una lingua che per chi desidera ampliare le conoscenze sviluppate nei percorsi scolastici'

        ]);
        $s1 = Post::create([
            'titulo'=>'quasi architect jñ ñ o beatae vitae dicta sunt explicabo. Nemo eore, cum sol nihil impedit',
            'contenido'=>' the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, 
            because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences 
            that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, 
            because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.
            To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of
            human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain
            the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but bec
            ause those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyo
            ne who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur 
            in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes labo
            rious physical exercise, except to obtain ',
            'imagen'=>"upload-posts/4GnlYKHTf78DgqLk5KPJaO8yUwI4as19gjsoz8uC.jpg",
            'titulo_en'=>'language. We offer texts and accompanying exercises that will test your',
            'contenido_en'=>'Interpretative skills are the foundation of interacting in the target language. We offer texts and accompanying exercises that will test your reading comprehension and improve your abilities to interpret vocabulary and cultural information in context. Exposure to authentic reading materials solidifies vocabulary recognition, provides access to varied sentence structures, and engages learners with intriguing cultural information and anecdotes. Interpretative skills are the foundation of interacting in the target language. We offer texts and accompanying exercises that will test your reading comprehension and improve your abilities to interpret vocabulary and cultural information in context. Exposure to authentic reading materials solidifies vocabulary recognition, provides access to varied sentence structures, and engages learners with intriguing cultural information and anecdotes.',
            'titulo_it'=>'straniere grazie a una stimolante tecnologia, disponibile sia per chi vuole',
            'contenido_it'=>'Qual è il tuo livello di comprensione di una lingua? Con il supporto del sito potrai accedere a numerosi testi e valutare la tua comprensione nella lettura grazie agli esercizi annessi Qual è il tuo livello di comprensione di una lingua? Con il supporto del sito potrai accedere a numerosi testi e valutare la tua comprensione nella lettura grazie agli esercizi annessi Qual è il tuo livello di comprensione di una lingua? Con il supporto del sito potrai accedere a numerosi testi e valutare la tua comprensione nella lettura grazie agli esercizi annessi'
        ]);
        $s1 = Post::create([
            'titulo'=>'d quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquia dolor',
            'contenido'=>' s est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere posth righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/fwuoNxGs7MVEbgMFN3BkrTUFDYhHmYIbcvy68r2u.jpg",
            'titulo_en'=>'reading comprehension and improve your abilities to interpret vocabulary',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'acquisire le basi di una lingua che per chi desidera ampliare le conoscenze',
            'contenido_it'=>'I testi variano per il livello di difficoltà: da quelli più semplici a quelli di livello intermedio ed elevato. I primi includono articoli e racconti adatti ai principianti, composti da vocaboli di base e contraddistinti da una grammatica semplice I testi variano per il livello di difficoltà: da quelli più semplici a quelli di livello intermedio ed elevato. I primi includono articoli e racconti adatti ai principianti, composti da vocaboli di base e contraddistinti da una grammatica semplice I testi variano per il livello di difficoltà: da quelli più semplici a quelli di livello intermedio ed elevato. I primi includono articoli e racconti adatti ai principianti, composti da vocaboli di base e contraddistinti da una grammatica semplice'

        ]);

        $s1 = Post::create([
            'titulo'=>'s est et expñkjk edita . Nam libero temporoluta nobis  optio cumque nihil impedit',
            'contenido'=>'th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/f4KzA5G89zpAAKLqK5uRMNLHCSjzh14LeqwhWGXg.jpg",
            'titulo_en'=>'and cultural information in context. Exposure to authentic reading',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'Qual è il tuo livello di comprensione di una lingua? Con il supporto del sito',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);
        $s1 = Post::create([
            'titulo'=>'quakj kk k si architecta sunt explicabo. Nemo eore, cum sol nihil impedit',
            'contenido'=>' the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, 
            because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences 
            that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, 
            because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.
            To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of
            human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain
            the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but bec
            ause those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyo
            ne who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur 
            in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes labo
            rious physical exercise, except to obtain ',
            'imagen'=>"upload-posts/4GnlYKHTf78DgqLk5KPJaO8yUwI4as19gjsoz8uC.jpg",
            'titulo_en'=>'materials solidifies vocabulary recognition, provides access to varied',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'potrai accedere a numerosi testi e valutare la tua comprensione nella',
            'contenido_it'=>' Hai inoltre la possibilità di utilizzare efficientemente questo strumento per concentrarti sui termini specifici di un dato contesto o argomento, salvando i vocaboli che vuoi approfondire nella tua lista personale Hai inoltre la possibilità di utilizzare efficientemente questo strumento per concentrarti sui termini specifici di un dato contesto o argomento, salvando i vocaboli che vuoi approfondire nella tua lista personale'

        ]);
        $s1 = Post::create([
            'titulo'=>' dolores eos ñlkjjl ñl qui ratione voluptatem sequi nesciunt. Neque porro quisquia dolor',
            'contenido'=>' s est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere posth righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/fwuoNxGs7MVEbgMFN3BkrTUFDYhHmYIbcvy68r2u.jpg",
            'titulo_en'=>'sentence structures, and engages learners with intriguing cultural',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'I testi variano per il livello di difficoltà: da quelli più semplici a quelli di',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);


        $s1 = Post::create([
            'titulo'=>'reñlkj ñlkj kj ññlrum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit',
            'contenido'=>'th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/f4KzA5G89zpAAKLqK5uRMNLHCSjzh14LeqwhWGXg.jpg",
            'titulo_en'=>'We offer a range of reading materials and text types at varied difficulty',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);
        $s1 = Post::create([
            'titulo'=>'quañlkj jl lñk si architecto beatae vitae dicta sunt explicabo. Nemo eore, cum sol nihil impedit',
            'contenido'=>' the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, 
            because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences 
            that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, 
            because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.
            To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of
            human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain
            the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but bec
            ause those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyo
            ne who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur 
            in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes labo
            rious physical exercise, except to obtain ',
            'imagen'=>"upload-posts/4GnlYKHTf78DgqLk5KPJaO8yUwI4as19gjsoz8uC.jpg",
            'titulo_en'=>'Our vocabulary builder tool will teach language learners new vocabulary',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'consolidare il tuo lessico. Questo strumento è in grado di riconoscere le',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);
        $s1 = Post::create([
            'titulo'=>'ñjlkj d quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquia dolor',
            'contenido'=>' s est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere posth righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/fwuoNxGs7MVEbgMFN3BkrTUFDYhHmYIbcvy68r2u.jpg",
            'titulo_en'=>'For learners who prefer to concentrate on specific topics, we empower you',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);

        $s1 = Post::create([
            'titulo'=>'s estt expedita libero tempoluta nobis  optiomque nihil impedit',
            'contenido'=>'th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/f4KzA5G89zpAAKLqK5uRMNLHCSjzh14LeqwhWGXg.jpg",
            'titulo_en'=>'to choose one of our previously created, contextualized vocabulary lists in',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'Hai inoltre la possibilità di utilizzare efficientemente questo strumento per',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);
        $s1 = Post::create([
            'titulo'=>'quasisunt expl Nemore, cum sol nihil impedit',
            'contenido'=>' the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, 
            because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences 
            that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, 
            because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.
            To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of
            human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain  the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain
            the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but bec
            ause those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyo
            ne who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur 
            in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes labo
            rious physical exercise, except to obtain ',
            'imagen'=>"upload-posts/4GnlYKHTf78DgqLk5KPJaO8yUwI4as19gjsoz8uC.jpg",
            'titulo_en'=>'should be fun and accessible to everyone. We develop exercises, content',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'Offriamo gli strumenti e le risorse necessari per l',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);
        $s1 = Post::create([
            'titulo'=>' di ratione volupsequi nescit. Neque porro quisquia dolor',
            'contenido'=>' s est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere posth righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse th righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse ',
            'imagen'=>"upload-posts/fwuoNxGs7MVEbgMFN3BkrTUFDYhHmYIbcvy68r2u.jpg",
            'titulo_en'=>'As part of our teaching philosophy, we believe that language learning',
            'contenido_en'=>'Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language. Our vocabulary builder tool will teach language learners new vocabulary while reviewing previously instructed words to encourage mastery. Our aims are to learn efficiently. As such, our process establishes a basis of key vocabulary, recognizes words you already know, and targets the words that require repeated use and more practice. Using this method, you will continue to solidify your vocabulary acquisition in the target language.',
            'titulo_it'=>'concentrarti sui termini specifici di un dato contesto o argomento,',
            'contenido_it'=>'A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci A tua disposizione troverai lo strumento lessicale per espandere e consolidare il tuo lessico. Questo strumento è in grado di riconoscere le parole e concentrarsi su di esse, consentendo di focalizzarsi sui termini più importanti e su quelli che ancora non conosci'

        ]);

        
        
        
    }
}
